### ISSUE TITLE
Quiz Questions Answers

### ISSUE THREAD

**Issue by lara3445** [rokalman/saving-by-the-second#8]
Some of the answers for the quiz questions are wrong. Here are the questions with the right answers:

How Many gallons (on average) does it take to fill a bathtub?
Right answer = 37 gallons

Per day how many gallons of water does an average American use?
Right answer = 80 - 100 gallons

What percent of indoor water use is showering/bathing?
Right answer = 27%

On average how many gallons does a shower use in 10 minutes?
Right answer = 20 gallons

How much of Earth's water is freshwater?
Right answer = 2%

**Comment by rokalman** [comment]
Resolved the issue.  WIll need to be re-deployed to see the results.
