### ISSUE TITLE
More Quiz Questions

### ISSUE THREAD

**Issue by lara3445** [rokalman/saving-by-the-second#9]
We have a few more quiz questions we would like to add to the app. Here they are with the correct answers:

Per year how many gallons of water does the United States use?
Right answer = 148 trillion gallons

During a 5 minute shower, what percent of water can a low flow shower head save?
Right answer = 40%

Per month how much water does the average person waist while waiting for their shower water to heat up?
Right answer = 200 - 300

In Japan where do people frequently bathe?
Right answer = In natural springs

In Turkey where do people frequently bathe?
Right answer = In Hammams

Once a week where do people on Finland shower?
Right answer = In a sauna

You can make up the other options for the questions, but if you want to know some ideas here is the link to a doc that has them all(the right answer on the doc is in the notes section).

**Comment by rokalman** [comment]
Added in the other quiz questions.  It will need to be deployed to see the changes
